// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForcarSincronizacao() {
  return window['go']['main']['App']['ForcarSincronizacao']();
}

export function ObterEstatisticasSync() {
  return window['go']['main']['App']['ObterEstatisticasSync']();
}
