// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BloquearLicenca(arg1, arg2) {
  return window['go']['main']['App']['BloquearLicenca'](arg1, arg2);
}

export function CriarLicenca(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CriarLicenca'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DesbloquearLicenca(arg1) {
  return window['go']['main']['App']['DesbloquearLicenca'](arg1);
}

export function ExcluirLicenca(arg1) {
  return window['go']['main']['App']['ExcluirLicenca'](arg1);
}

export function GerarSerial() {
  return window['go']['main']['App']['GerarSerial']();
}

export function ListarLicencas() {
  return window['go']['main']['App']['ListarLicencas']();
}
