// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BloquearLicenca(arg1:string,arg2:string):Promise<main.ApiResponse>;

export function CriarLicenca(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<main.ApiResponse>;

export function DesbloquearLicenca(arg1:string):Promise<main.ApiResponse>;

export function ExcluirLicenca(arg1:string):Promise<main.ApiResponse>;

export function GerarSerial():Promise<string>;

export function ListarLicencas():Promise<main.ApiResponse>;
